version: '3.8'
services:
  watcher:
    container_name: watcher
    build:
      context: ../
      dockerfile: ./svc/watcher/Dockerfile
    ports:
      - "18080:8080"
    environment:
      TYPE: webpage
      ENDPOINT: https://www.google.com
      INTERVAL: 15s

  genie:
    container_name: genie
    build:
      context: ../
      dockerfile: ./svc/genie/Dockerfile
    ports:
      - "18081:8081"
    volumes:
      - ./minikube/config:/root/.kube/config

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "19090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "13000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  prom_data:
