apiVersion: statuz.timam.io/v1alpha1
kind: Statuz
metadata:
  name: anyGivenName
  description: anyGivenDescription
  namespace: yourNamespace                         #statuz will create resources(pod,configmap etc) in this namespace to monitor specified endpoint
spec:
  type: http                                       #["http", "https", "ping", "port"]
  run:
    cluster: self                                  #["self", "remote", "cloud"]
  monitor:
    endpoint: https://grafana.com/healthz          #["https://grafana.com/healthz", "prometheus.monitoring.svc.cluster.local", "8.8.8.8", "1.1.1.1:53" ]
    interval: 15s                                  #["15s", "30s", "60s", "300s"]
